// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package dbsqlc

import (
	"context"
)

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings
WHERE key = $1
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteAppSetting, key)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, created_at, updated_at
FROM app_settings
WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value
RETURNING key, value, created_at, updated_at
`

type UpsertAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertAppSetting, arg.Key, arg.Value)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
