// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_profiles.sql

package dbsqlc

import (
	"context"
)

const createModelProfile = `-- name: CreateModelProfile :one
INSERT INTO model_profiles (
  id,
  name,
  provider,
  model_id,
  base_url,
  api_key,
  api_key_env,
  context_window,
  max_output_tokens,
  temperature,
  timeout_seconds,
  metadata
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    model_id = EXCLUDED.model_id,
    base_url = EXCLUDED.base_url,
    api_key = EXCLUDED.api_key,
    api_key_env = EXCLUDED.api_key_env,
    context_window = EXCLUDED.context_window,
    max_output_tokens = EXCLUDED.max_output_tokens,
    temperature = EXCLUDED.temperature,
    timeout_seconds = EXCLUDED.timeout_seconds,
    metadata = model_profiles.metadata || EXCLUDED.metadata,
    deleted_at = NULL,
    status = 'active'
RETURNING id, name, provider, model_id, base_url, api_key_env, context_window, max_output_tokens, temperature, timeout_seconds, status, metadata, created_at, updated_at, deleted_at, api_key
`

type CreateModelProfileParams struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Provider        string  `json:"provider"`
	ModelID         string  `json:"model_id"`
	BaseUrl         string  `json:"base_url"`
	ApiKey          string  `json:"api_key"`
	ApiKeyEnv       string  `json:"api_key_env"`
	ContextWindow   int32   `json:"context_window"`
	MaxOutputTokens int32   `json:"max_output_tokens"`
	Temperature     float64 `json:"temperature"`
	TimeoutSeconds  int32   `json:"timeout_seconds"`
	Metadata        []byte  `json:"metadata"`
}

func (q *Queries) CreateModelProfile(ctx context.Context, arg CreateModelProfileParams) (ModelProfile, error) {
	row := q.db.QueryRow(ctx, createModelProfile,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.ModelID,
		arg.BaseUrl,
		arg.ApiKey,
		arg.ApiKeyEnv,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Temperature,
		arg.TimeoutSeconds,
		arg.Metadata,
	)
	var i ModelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ModelID,
		&i.BaseUrl,
		&i.ApiKeyEnv,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.TimeoutSeconds,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApiKey,
	)
	return i, err
}

const deleteModelProfile = `-- name: DeleteModelProfile :exec
UPDATE model_profiles
SET deleted_at = now(), status = 'deleted'
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteModelProfile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteModelProfile, id)
	return err
}

const getModelProfile = `-- name: GetModelProfile :one
SELECT id, name, provider, model_id, base_url, api_key_env, context_window, max_output_tokens, temperature, timeout_seconds, status, metadata, created_at, updated_at, deleted_at, api_key
FROM model_profiles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetModelProfile(ctx context.Context, id string) (ModelProfile, error) {
	row := q.db.QueryRow(ctx, getModelProfile, id)
	var i ModelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ModelID,
		&i.BaseUrl,
		&i.ApiKeyEnv,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.TimeoutSeconds,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApiKey,
	)
	return i, err
}

const listModelProfiles = `-- name: ListModelProfiles :many
SELECT id, name, provider, model_id, base_url, api_key_env, context_window, max_output_tokens, temperature, timeout_seconds, status, metadata, created_at, updated_at, deleted_at, api_key
FROM model_profiles
WHERE deleted_at IS NULL
ORDER BY updated_at DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListModelProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListModelProfiles(ctx context.Context, arg ListModelProfilesParams) ([]ModelProfile, error) {
	rows, err := q.db.Query(ctx, listModelProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelProfile{}
	for rows.Next() {
		var i ModelProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.ModelID,
			&i.BaseUrl,
			&i.ApiKeyEnv,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Temperature,
			&i.TimeoutSeconds,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ApiKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelProfile = `-- name: UpdateModelProfile :one
UPDATE model_profiles
SET name = $2,
    provider = $3,
    model_id = $4,
    base_url = $5,
    api_key = $6,
    api_key_env = $7,
    context_window = $8,
    max_output_tokens = $9,
    temperature = $10,
    timeout_seconds = $11,
    status = $12,
    metadata = $13
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, provider, model_id, base_url, api_key_env, context_window, max_output_tokens, temperature, timeout_seconds, status, metadata, created_at, updated_at, deleted_at, api_key
`

type UpdateModelProfileParams struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Provider        string  `json:"provider"`
	ModelID         string  `json:"model_id"`
	BaseUrl         string  `json:"base_url"`
	ApiKey          string  `json:"api_key"`
	ApiKeyEnv       string  `json:"api_key_env"`
	ContextWindow   int32   `json:"context_window"`
	MaxOutputTokens int32   `json:"max_output_tokens"`
	Temperature     float64 `json:"temperature"`
	TimeoutSeconds  int32   `json:"timeout_seconds"`
	Status          string  `json:"status"`
	Metadata        []byte  `json:"metadata"`
}

func (q *Queries) UpdateModelProfile(ctx context.Context, arg UpdateModelProfileParams) (ModelProfile, error) {
	row := q.db.QueryRow(ctx, updateModelProfile,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.ModelID,
		arg.BaseUrl,
		arg.ApiKey,
		arg.ApiKeyEnv,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Temperature,
		arg.TimeoutSeconds,
		arg.Status,
		arg.Metadata,
	)
	var i ModelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ModelID,
		&i.BaseUrl,
		&i.ApiKeyEnv,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.TimeoutSeconds,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApiKey,
	)
	return i, err
}
