// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbsqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, storage_provider, storage_bucket, storage_prefix, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    storage_provider = EXCLUDED.storage_provider,
    storage_bucket = EXCLUDED.storage_bucket,
    storage_prefix = EXCLUDED.storage_prefix,
    metadata = projects.metadata || EXCLUDED.metadata,
    deleted_at = NULL
RETURNING id, name, description, status, storage_provider, storage_bucket, storage_prefix, metadata, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	StorageProvider string `json:"storage_provider"`
	StorageBucket   string `json:"storage_bucket"`
	StoragePrefix   string `json:"storage_prefix"`
	Metadata        []byte `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StorageProvider,
		arg.StorageBucket,
		arg.StoragePrefix,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePrefix,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = now(), status = 'deleted'
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, status, storage_provider, storage_bucket, storage_prefix, metadata, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePrefix,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectDocuments = `-- name: ListProjectDocuments :many
SELECT id, project_id, kind, title, body, metadata, created_at, updated_at, deleted_at
FROM project_documents
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY
  CASE kind
    WHEN 'project_brief' THEN 1
    WHEN 'reader_contract' THEN 2
    WHEN 'style_guide' THEN 3
    WHEN 'taboo' THEN 4
    WHEN 'world_rules' THEN 5
    WHEN 'power_system' THEN 6
    WHEN 'factions' THEN 7
    WHEN 'locations' THEN 8
    WHEN 'mainline' THEN 9
    WHEN 'current_state' THEN 10
    ELSE 100
  END,
  updated_at DESC
`

func (q *Queries) ListProjectDocuments(ctx context.Context, projectID string) ([]ProjectDocument, error) {
	rows, err := q.db.Query(ctx, listProjectDocuments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectDocument{}
	for rows.Next() {
		var i ProjectDocument
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, status, storage_provider, storage_bucket, storage_prefix, metadata, created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
ORDER BY updated_at DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StorageProvider,
			&i.StorageBucket,
			&i.StoragePrefix,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2,
    description = $3,
    status = $4,
    storage_provider = $5,
    storage_bucket = $6,
    storage_prefix = $7,
    metadata = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, status, storage_provider, storage_bucket, storage_prefix, metadata, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	Status          string `json:"status"`
	StorageProvider string `json:"storage_provider"`
	StorageBucket   string `json:"storage_bucket"`
	StoragePrefix   string `json:"storage_prefix"`
	Metadata        []byte `json:"metadata"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StorageProvider,
		arg.StorageBucket,
		arg.StoragePrefix,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePrefix,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertProjectDocument = `-- name: UpsertProjectDocument :one
INSERT INTO project_documents (project_id, kind, title, body, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, kind) WHERE deleted_at IS NULL DO UPDATE
SET title = EXCLUDED.title,
    body = EXCLUDED.body,
    metadata = project_documents.metadata || EXCLUDED.metadata
RETURNING id, project_id, kind, title, body, metadata, created_at, updated_at, deleted_at
`

type UpsertProjectDocumentParams struct {
	ProjectID string `json:"project_id"`
	Kind      string `json:"kind"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Metadata  []byte `json:"metadata"`
}

func (q *Queries) UpsertProjectDocument(ctx context.Context, arg UpsertProjectDocumentParams) (ProjectDocument, error) {
	row := q.db.QueryRow(ctx, upsertProjectDocument,
		arg.ProjectID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Metadata,
	)
	var i ProjectDocument
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
