// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, session_id, input, status, metadata)
VALUES ($1, $2, $3, 'running', $4)
RETURNING id, project_id, session_id, input, final_text, run_dir, status, error, metadata, created_at, updated_at
`

type CreateRunParams struct {
	ProjectID pgtype.Text `json:"project_id"`
	SessionID pgtype.Int8 `json:"session_id"`
	Input     string      `json:"input"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.SessionID,
		arg.Input,
		arg.Metadata,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.Input,
		&i.FinalText,
		&i.RunDir,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRun = `-- name: FailRun :one
UPDATE runs
SET status = 'failed',
    error = $2
WHERE id = $1
RETURNING id, project_id, session_id, input, final_text, run_dir, status, error, metadata, created_at, updated_at
`

type FailRunParams struct {
	ID    int64  `json:"id"`
	Error string `json:"error"`
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, failRun, arg.ID, arg.Error)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.Input,
		&i.FinalText,
		&i.RunDir,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :one
UPDATE runs
SET final_text = $2,
    run_dir = $3,
    status = 'completed',
    error = ''
WHERE id = $1
RETURNING id, project_id, session_id, input, final_text, run_dir, status, error, metadata, created_at, updated_at
`

type FinishRunParams struct {
	ID        int64  `json:"id"`
	FinalText string `json:"final_text"`
	RunDir    string `json:"run_dir"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, finishRun, arg.ID, arg.FinalText, arg.RunDir)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.Input,
		&i.FinalText,
		&i.RunDir,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
